### ISSUE TITLE
== / hashcode

### ISSUE THREAD

**Issue by Lootwig** [Jim-Eckerlein/dart-angles#1]
I recently switched from "manually" storing degrees as doubles to using this package. I only noticed later that the lack of overrides for equality/hashcode of angles led to unexpected behaviour, is this intended? Especially since the "compareTo" method is implemented such that it cannot return 0 for angles of equal values (other than instance identity).

**Comment by jim-ec** [comment]
Well, you cannot really test IEEE 754 floating points for equality, so it does not really make sense to provide a way to test for value-equality.

I've still implemented it, together with a approximation comparision, testing an angle withing a given acceptance range. The angle class now provides both, a hash code and a comparision operator.

Thank you for pointing out that issue and please feel free to create a pull request if you see something that's definitely missing in the angle class.

**Comment by Lootwig** [comment]
Great, thanks for the quick response. Are you going to release the pub version soon as well or should I let my pubspec point to github instead?

**Comment by Lootwig** [comment]
Note: current version number does not allow adding this package as a dependency, dart pub requires semantic versioning (three-digit version number).

**Comment by jim-ec** [comment]
So, the new version 1.2.1 is uploaded to pub. I also tagged the git commit with a three-digit version, but it's probably better use the pub served version anyway.
